# Generated by Django 5.0.6 on 2024-06-03 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='TOC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
